// this lead to error
enum note {WHOLE, HALF, QUARTER, EIGHTH, SIXTEENTH, THIRTY_SECOND, SIXTY_FOURTH, D_WHOLE, D_HALF, D_QUARTER, D_EIGHTH, D_SIXTEENTH, D_THIRTY_SECOND, D_SIXTY_FOURTH};
void controlNote(double);
